name: 'Android Emulator Setup'
description: 'Sets up an Android SDK, creates an emulator, and starts it.'
runs:
  using: 'composite'
  steps:
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Install Android SDK
      run: |
        sudo apt-get update  > /dev/null 2>&1
        sudo apt-get install -y wget unzip  > /dev/null 2>&1
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip  > /dev/null 2>&1
        mkdir -p $HOME/android-sdk/cmdline-tools  > /dev/null 2>&1
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools  > /dev/null 2>&1
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools  > /dev/null 2>&1
      shell: bash

    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
      shell: bash

    - name: Check Ubuntu environment variables
      run: |
        echo $ANDROID_HOME
        echo $PATH
      shell: bash

    - name: Accept Android SDK licenses interactively
      run: yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses  > /dev/null 2>&1 || true
      shell: bash

    - name: Install SDK package
      run: |
        $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "system-images;android-33;google_apis;x86_64" "emulator"  > /dev/null 2>&1
      shell: bash

    - name: Create emulator
      run: |
        echo "no" | $HOME/android-sdk/cmdline-tools/tools/bin/avdmanager create avd -n emu -k "system-images;android-33;google_apis;x86_64" --device "pixel"  > /dev/null 2>&1
      shell: bash

    - name: Start Android emulator
      run: |
        nohup $HOME/android-sdk/emulator/emulator -avd emu -no-snapshot-save -no-boot-anim -wipe-data -no-window -gpu off &
        $ANDROID_HOME/platform-tools/adb wait-for-device
      shell: bash

    - name: Check list devices
      run: |
        $ANDROID_HOME/platform-tools/adb devices
      shell: bash
